### ISSUE TITLE
Iceberg renderer crashes with Sodium 0.4.9 when displaying tooltips with Legendary Tooltips installed

### ISSUE THREAD

**Issue by Timolino456** [AHilyard/Iceberg#21]
See https://github.com/CaffeineMC/sodium-fabric/issues/1602, the crash report attached there and JellySquids comment. I can't really add anything else but I wanted to let you know of the issue.

**Comment by ydoc5212** [comment]
Same issue! helpful thread, thanks! Will uninstall iceberg and legendary tooltips for now :P

**Comment by AHilyard** [comment]
Thanks for creating this, I've received a lot of reports about it recently.  I've determined the cause of the crash and prepared a fix for it, however version 0.4.10 of Sodium will be coming out soon(ish?) which will break my fix.  I am going to hold off on releasing an updated Iceberg build with a fix until Sodium releases version 0.4.10 because of this.
In the meantime, you can either downgrade Sodium to version 0.4.8 or disable 3D item previews in Legendary Tooltips if you want to continue using both mods.

**Comment by AHilyard** [comment]
Yes, this is the same issue.

**Comment by exultiaa** [comment]
> In the meantime, you can either downgrade Sodium to version 0.4.8 or disable 3D item previews in Legendary Tooltips if you want to continue using both mods.

how would one disable 3D item previews? i could just have missed it entirely, but i didn't see an option for it in the config.

**Comment by AHilyard** [comment]
> > In the meantime, you can either downgrade Sodium to version 0.4.8 or disable 3D item previews in Legendary Tooltips if you want to continue using both mods.
> 
> how would one disable 3D item previews? i could just have missed it entirely, but i didn't see an option for it in the config.

Set the `render_item_model` option to `"NONE"`.

**Comment by exultiaa** [comment]
ahh, okay sorry. thank you!
