### ISSUE TITLE
[1.16.5] crash caused at "onClick" event

### ISSUE THREAD

**Issue by SteamDoge9000** [AHilyard/Iceberg#4]
**Describe the bug**
Sometimes when you exit the game or click on a button quickly, the game will crash on you
**To Reproduce**
IN actuality, it may be hard to reproduce this issue, their is a method but even that takes some chance, even then its random

**Expected behavior**
should be obvious

**Screenshots**

**Environment (please complete the following information):**
 
 all other data should be provided in the crashlog,
Game modloader: FORGE
Game Instance: Forge 1.16.5 - ver. 36.2.22
Mod Version: Iceberg-1.16.5-1.0.34.jar

**Log files**
Please attach your latest.log file as a file attachment, that was generated when the problem occurred.  If a crash is occurring, also attach your crash log file as a file attachment.

[crash-2022-01-09_03.48.17-client.txt](https://github.com/AHilyard/Iceberg/files/7834716/crash-2022-01-09_03.48.17-client.txt)

**Additional context**
Add any other notes or context about the problem here.  e.g. If it worked previously, what changed about your setup?  Are you playing single player or multiplayer?  Etc.

none really noticeable, though this was single player and it might have started a month ago? idk

**Comment by AHilyard** [comment]
I don't see any indication that Iceberg is involved with this crash from the crash log.  Was there anything else that made you think it was Iceberg causing it?  From the crash log it looks like it's being caused by Epic Fight:
`at yesman.epicfight.client.gui.HealthBarIndicator.shouldDraw(HealthBarIndicator.java:34) ~[?:1.0] {re:classloading,pl:runtimedistcleaner:A}`

In fact, looking at the Epic Fight code, this function (https://github.com/Yesssssman/epicfightmod/blob/master/src/main/java/yesman/epicfight/client/gui/HealthBarIndicator.java#L29-L50) needs to be checking if the render view entity has been destroyed already on line 34 (which would happen when the game is shutting down).  I recommend opening an issue on that mod.
