### ISSUE TITLE
Remove Embeddium check for vertex collector service

### ISSUE THREAD

**Issue by embeddedt** [AHilyard/Iceberg#80]
Hi there!

Since Embeddium compat has been removed in the latest Iceberg release, could you remove the check for it here...

https://github.com/AHilyard/Iceberg/blob/52be22f91f30eac0b440259f2926b6bc86e864af/common/src/main/java/com/anthonyhilyard/iceberg/renderer/VertexCollector.java#L38-L39

...so that your logic will fall back to using vanilla `VertexConsumer`s, rather than crashing with Embeddium installed due to trying to load a Sodium class?

**Comment by NovaViper** [comment]
I'm actually curious.. why was Embeddium support removed? I hate to be mean but if this sort of update is going to be made, **at the very least** make sure that it doesn't result in the game crashing or put a warning on the mod's front page about such breaking change. Spent a good 5 hours trying to figure out why suddenly my private server broke only to discover it was this particular update, not something fun to deal with at all.

**Comment by embeddedt** [comment]
It seems they want to focus on Sodium 0.6 support, which is fine, as Embeddium should be able to work fine with their fallback vanilla logic. Continuing to use the Sodium logic with Embeddium installed seems to be an oversight.

**Comment by AHilyard** [comment]
Apologies for the oversight, an update is currently pending that will fix this crash.
@NovaViper Because the Sodium API has diverged from the Embeddium API, and supporting both is not realistic at this time.  Perhaps in the future. The changelog of the most recent Iceberg update indicated that Embeddium was no longer supported, that is a good first place to check in the future.
